/*
 * Swagger DS/CS 519 Assessment - OpenAPI 3.0
 *
 * This is the grading API for the course assessment.   Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: nagendra@bu.edu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace AzureFunction
{ 
    public class SamFact {
        public string text {get; set; }
        public string id { get; set; }
    }
}
